apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-oversubscribed-job
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gpu-training
          image: gcr.io/ai-research-e44f/training-image:latest
          resources:
            limits:
              nvidia.com/gpu: 4  # Requests more GPUs than available on a single node