{
 "title": "GPU-Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PCIe Throughput (Bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PCIE_RX_BYTES + DCGM_FI_PROF_PCIE_TX_BYTES",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(DCGM_FI_DEV_FB_USED)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "__auto" }
   ]
  }
 ]
}