apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mpi-operator-rolebinding
  namespace: kubeflow
subjects:
- kind: ServiceAccount
  name: mpi-operator
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: mpi-operator
  apiGroup: rbac.authorization.k8s.io
