apiVersion: batch/v1
kind: Job
metadata:
  name: faulty-job
spec:
  template:
    metadata:
      labels:
        job: faulty-job
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/arch: amd64  # Forces scheduling on an AMD64 node
      containers:
        - name: test-container
          image: arm64v8/python  # ARM64 image will fail on AMD64 nodes
          command: ["python3"]
          args: ["-c", "print('Hello from Python!')"]